# Generated by Django 4.2.1 on 2023-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del director', max_length=64)),
                ('apellido', models.CharField(help_text='Apellido del director', max_length=64)),
            ],
        ),
    ]
