# Generated by Django 4.2.1 on 2023-05-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Pelicula', max_length=64)),
                ('descripcion', models.CharField(help_text='Descripción de la Pelicula', max_length=250)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
